/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/sakiib/crd/pkg/apis/book.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBookAPIs implements BookAPIInterface
type FakeBookAPIs struct {
	Fake *FakeBookV1alpha1
	ns   string
}

var bookapisResource = schema.GroupVersionResource{Group: "book.com", Version: "v1alpha1", Resource: "bookapis"}

var bookapisKind = schema.GroupVersionKind{Group: "book.com", Version: "v1alpha1", Kind: "BookAPI"}

// Get takes name of the bookAPI, and returns the corresponding bookAPI object, and an error if there is any.
func (c *FakeBookAPIs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BookAPI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bookapisResource, c.ns, name), &v1alpha1.BookAPI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BookAPI), err
}

// List takes label and field selectors, and returns the list of BookAPIs that match those selectors.
func (c *FakeBookAPIs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BookAPIList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bookapisResource, bookapisKind, c.ns, opts), &v1alpha1.BookAPIList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BookAPIList{ListMeta: obj.(*v1alpha1.BookAPIList).ListMeta}
	for _, item := range obj.(*v1alpha1.BookAPIList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bookAPIs.
func (c *FakeBookAPIs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bookapisResource, c.ns, opts))

}

// Create takes the representation of a bookAPI and creates it.  Returns the server's representation of the bookAPI, and an error, if there is any.
func (c *FakeBookAPIs) Create(ctx context.Context, bookAPI *v1alpha1.BookAPI, opts v1.CreateOptions) (result *v1alpha1.BookAPI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bookapisResource, c.ns, bookAPI), &v1alpha1.BookAPI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BookAPI), err
}

// Update takes the representation of a bookAPI and updates it. Returns the server's representation of the bookAPI, and an error, if there is any.
func (c *FakeBookAPIs) Update(ctx context.Context, bookAPI *v1alpha1.BookAPI, opts v1.UpdateOptions) (result *v1alpha1.BookAPI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bookapisResource, c.ns, bookAPI), &v1alpha1.BookAPI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BookAPI), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBookAPIs) UpdateStatus(ctx context.Context, bookAPI *v1alpha1.BookAPI, opts v1.UpdateOptions) (*v1alpha1.BookAPI, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bookapisResource, "status", c.ns, bookAPI), &v1alpha1.BookAPI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BookAPI), err
}

// Delete takes name of the bookAPI and deletes it. Returns an error if one occurs.
func (c *FakeBookAPIs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bookapisResource, c.ns, name), &v1alpha1.BookAPI{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBookAPIs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bookapisResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BookAPIList{})
	return err
}

// Patch applies the patch and returns the patched bookAPI.
func (c *FakeBookAPIs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BookAPI, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bookapisResource, c.ns, name, pt, data, subresources...), &v1alpha1.BookAPI{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BookAPI), err
}
