/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	bookcomv1alpha1 "github.com/sakiib/crd/pkg/apis/book.com/v1alpha1"
	versioned "github.com/sakiib/crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/sakiib/crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/sakiib/crd/pkg/client/listers/book.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BookAPIInformer provides access to a shared informer and lister for
// BookAPIs.
type BookAPIInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BookAPILister
}

type bookAPIInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBookAPIInformer constructs a new informer for BookAPI type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBookAPIInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBookAPIInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBookAPIInformer constructs a new informer for BookAPI type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBookAPIInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BookV1alpha1().BookAPIs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BookV1alpha1().BookAPIs(namespace).Watch(context.TODO(), options)
			},
		},
		&bookcomv1alpha1.BookAPI{},
		resyncPeriod,
		indexers,
	)
}

func (f *bookAPIInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBookAPIInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bookAPIInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bookcomv1alpha1.BookAPI{}, f.defaultInformer)
}

func (f *bookAPIInformer) Lister() v1alpha1.BookAPILister {
	return v1alpha1.NewBookAPILister(f.Informer().GetIndexer())
}
